#!/usr/bin/env groovy
properties([pipelineTriggers([githubPush()])])

pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                dir('backend') {                 
                  sh 'mvn clean package -DskipTests' 
                }
           }
        }
        stage('Start SQL') { 
            steps {
              sh 'docker start nexum-db'
           }
       }
        stage('Deploy') { 
            environment {            
                APP_JAVA = 'backend-0.0.1-SNAPSHOT.jar'
                APP_PATH = "/home/ubuntu/deploy/"
                SCRIPT_START = "deploy-java.sh"
            }        
            steps {
             sh 'java -version'

              dir('backend') { 
                 sh "cp -f target/$APP_JAVA $APP_PATH"
              }            

              sh "$APP_PATH$SCRIPT_START"
           }
       }
   }
}
