version: "3.4"
services:
  nexum_docker:
    image: node:alpine
    container_name: nexum-front
    entrypoint: ["npm"]
    command: ["run","dev", "--","--host"]
    ports:
      - 80:80
    working_dir: /app
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
