#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('Build') { 
            stedir('front') { 
              sh 'npm install' 
              sh 'npm run build' 
            }
        }
    }
}
