#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('Build') { 
            steps {
                sh 'cd front'
                sh 'npm install' 
                sh 'npm run build'
            }
        }
    }
}