
		INSERT INTO TB_USERS (NOME, EMAIL, SENHA, CELULAR, IS_LOGGED) VALUES
		('Guilherme','guilherme@hotmail.com', '123' ,'11 997368699', false);

		INSERT INTO TB_ROLE (ROLE_NAME) VALUES
		('ROLE_ADMIN'),('ROLE_CONTRATANTE'),('ROLE_FREELANCER');

		INSERT INTO TB_USERS_ROLES (ID_USUARIO, ID_ROLE) VALUES
		(1,1);

		INSERT INTO TB_HABILIDADE (NOME) VALUES
		('FIGMA');

		INSERT INTO TB_FREELANCER (ID_USUARIO) VALUES
		(1);

		INSERT INTO TB_USERS_HABILIDADES (ID_USUARIO, ID_HABILIDADE) VALUES
		(1,1);

		INSERT INTO TB_SOCIAL (NOME) VALUES
		('Facebook');

		INSERT INTO TB_SOCIAL_USER (USER_URL, ID_SOCIAL, ID_USUARIO) VALUES
		('GUILHEMRE.FACEBOOK', 1, 1);

		INSERT INTO TB_ENDERECO (CIDADE, ESTADO, id_usuario) VALUES
		('Ribeirão Pires', 'São Paulo', 1);




